### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by justinmoon** [kas-gui/kas#249] opened 2021-09-23 05:07 UTC
I'm on arch linux:

```
$ cargo run --example gallery
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/examples/gallery`
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [4], size: Constant([6]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [4], size: Constant([6]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [4], size: Constant([6]), stride: 4 }
[2021-09-23T05:00:46Z ERROR wgpu_core::validation] Unexpected varying type: Array { base: [4], size: Constant([6]), stride: 4 }
MESA-INTEL: error: ../mesa-21.2.1/src/intel/vulkan/anv_batch_chain.c:2053: execbuf2 failed: Invalid argument (VK_ERROR_DEVICE_LOST)
thread 'main' panicked at 'Error in Queue::submit: parent device is lost', /home/justin/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.10.1/src/backend/direct.rs:186:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-09-23T05:00:46Z ERROR wgpu_core::device] failed to wait for the device: Lost
```

Not sure if I installed dependencies correctly ...

**Comment by dhardy** [comment] 2021-09-23 09:04
So you're using Intel graphics. Which CPU generation? Can you try running some [wgpu](https://github.com/gfx-rs/wgpu) examples?

**Comment by justinmoon** [comment] 2021-09-23 16:25
Yes Intel. Skylake. I get the same error when I try to run wgpu's "mipmap" example. But all the other ones I tried worked.

**Comment by dhardy** [comment] 2021-09-23 17:09
I just tested on my Intel Haswell laptop.. and it doesn't draw (though no obvious error). Will have to investigate further. You might also consider reporting an issue to WGPU. [See here](https://github.com/gfx-rs/wgpu/wiki/Debugging-wgpu-Applications) if you wish to investigate further yourself.

**Comment by dhardy** [comment] 2021-10-12 07:04
I can confirm that the update to WGPU 0.10 is what broke rendering on the Haswell laptop. I see WGPU 0.11 is out now, so testing that is next..

**Comment by dhardy** [comment] 2022-02-23 14:32
Closing because this largely concerns WGPU and I do not have the capacity to work on this directly.

Instead non-WGU rendering (#287) should solve this (eventually).

**Closed by dhardy** 2022-02-23 14:32 UTC
